services:
  mdbook-service:
    container_name: mdbook-container
    image: lethang7794/mdbook:v0.4.40-amd64
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ${PWD}:/app
    command:
      - mdbook
      - serve
      - --hostname
      - "0.0.0.0"
      - --watcher
      - native
